### ISSUE TITLE
Pass function

### ISSUE THREAD

**Issue by antoniohuertas** [mobilityhouse/ocpp#213]
hello, could you give me an example of how to proceed with the functions that make pass. For example StatusNotification. 

I have implemented for the ChargeStation script:

    async def Status_Notification(self):
        request=call.StatusNotificationPayload(timestamp='marcadetiempo', connector_status='Available', evse_id=1111, 
            connector_id=1111)
        await self.call(request)

and for the CentralStation script I have implemented:

    @on('StatusNotification')
    async def on_Status_Notification(self, timestamp, connector_status, evse_id, connector_id, **kwargs):
        pass

I understand that the problem is in AWAIT, because it is waiting for an answer that does not arrive.

Thank you very much for the help, I am starting to use the library and I have many doubts because there are not enough examples and my knowledge of Python is limited, if someone could send me more information or some scripts already implemented I would appreciate it.

**Comment by laysauchoa** [comment]
Hi @antoniohuertas 

Congrats :tada: in starting with Python and the OCPP python library.

First of all, I will divide my comments in two sections: python related and OCPP related, so it is not confusing when we go through the points. 

Python:
- Python uses the PEP8 guidelines, therefore, name of functions should be in the `lower_case_with_underscores` style. Check it [PEP 8](https://www.python.org/dev/peps/pep-0008/)
- You await function is correct but your decorator is not; therefore, this message is not received on the central system code. You are missing the `Action` word. You can check how it is done for `BootNotification` in the [example](https://github.com/mobilityhouse/ocpp/blob/master/examples/v16/central_system.py#L24)

Code example:
OCPP:
- You have arguments which are not part of the StatusNotificationPayload like `evse_id` or `connector_status`. Check how the StatusNotificationPayload is implemented [here](https://github.com/mobilityhouse/ocpp/blob/fdfb5b1b33665dad13708b47226f48b56ee6b438/ocpp/v16/call.py#L213)
-  As a general tip, it is a good idea to open the OCPP manual and follow with the code the functions you are trying to implement (for e.g., page 46, OCPP 1.6 [manual](https://github.com/mobilityhouse/ocpp/blob/master/docs/v16/ocpp-1.6.pdf)

- dateTime is format date-time as string, so your value should not have passed the validation. However, the validation does not fails, weird.

CP
```
    async def send_status_notification(self):
        request = call.StatusNotificationPayload(
            connector_id=1, error_code='NoError', status='Available')
        response = await self.call(request)
```

Central system
```
    @on(Action.StatusNotification)
    async def on_status_notification(self, connector_id: int,
                                     error_code: str, status: str, **kwargs) -> Dict:
        logging.info("status: %s, error_code: %s, optional: %s", status, error_code, kwargs)
        return call_result.StatusNotificationPayload()
```
Running:
```
✦ ➜ python3 charge_point.py 
INFO:ocpp:CP_1: send [2,"2c329bdc-b86a-473e-848c-2510158bf3ca","BootNotification",{"chargePointModel":"Optimus","chargePointVendor":"The Mobility House"}]
INFO:ocpp:CP_1: receive message [3,"2c329bdc-b86a-473e-848c-2510158bf3ca",{"currentTime":"2021-06-13T08:30:40.465251","interval":10,"status":"Accepted"}]
Connected to central system.
INFO:ocpp:CP_1: send [2,"d9df42c7-60ba-43c0-bc43-fc8c2c09d22a","StatusNotification",{"connectorId":1,"errorCode":"NoError","status":"Available"}]
INFO:ocpp:CP_1: receive message [3,"d9df42c7-60ba-43c0-bc43-fc8c2c09d22a",{}]
```

```
✦ ➜ python3 central_system.py 
INFO:root:Server Started listening to new connections...
INFO:root:Protocols Matched: ocpp1.6
INFO:ocpp:CP_1: receive message [2,"2c329bdc-b86a-473e-848c-2510158bf3ca","BootNotification",{"chargePointModel":"Optimus","chargePointVendor":"The Mobility House"}]
INFO:ocpp:CP_1: send [3,"2c329bdc-b86a-473e-848c-2510158bf3ca",{"currentTime":"2021-06-13T08:30:40.465251","interval":10,"status":"Accepted"}]
INFO:ocpp:CP_1: receive message [2,"d9df42c7-60ba-43c0-bc43-fc8c2c09d22a","StatusNotification",{"connectorId":1,"errorCode":"NoError","status":"Available"}]
INFO:root:status: Available, error_code: NoError, optional: {}
INFO:ocpp:CP_1: send [3,"d9df42c7-60ba-43c0-bc43-fc8c2c09d22a",{}]
```

**Comment by antoniohuertas** [comment]
Hello @laysauchoa! First of all, I would like to thank you for your time and for helping me. 


I have seen that the indications that you give me are for v1.6 of OCPP, I am implementing version 2.0.1.  I have adapted the indications you have given me and the tips to my version and the code is working correctly. 

I have implemented for the ChargeStation script:

    @on('StatusNotification')
    async def on_statusnotif(self, timestamp, connector_status, evse_id, connector_id, **kwargs):
        return call_result.StatusNotificationPayload()


and for the CentralStation script I have implemented:

    async def send_status_notification(self):
        request = call.StatusNotificationPayload(timestamp='marcadetiempo', connector_status='Available', evse_id=1, connector_id=1)
        response = await self.call(request)


I still don't know why 'timestamp' works, if it should be in date-time format as you told me. 
Do you think I should change something in the code? I send and receive the same messages that you gave me in the example. 



Thank you very much again, we will keep talking .

**Comment by laysauchoa** [comment]
@antoniohuertas I have reported it in the issue as a [bug](https://github.com/mobilityhouse/ocpp/issues/216). It should not allow you to send a string by itself but a string in the date-time format. 

I was only able to fix the tests [on this PR](https://github.com/mobilityhouse/ocpp/pull/214/files) but still does not fail in the implementation. By the way, check this [issue](https://github.com/Julian/jsonschema/issues/395), some extra libraries are required to make format checked active.

**Comment by tropxy** [comment]
> Hi @antoniohuertas
> 
> Congrats 🎉 in starting with Python and the OCPP python library.
> 
> First of all, I will divide my comments in two sections: python related and OCPP related, so it is not confusing when we go through the points.
> 
> Python:
> 
> * Python uses the PEP8 guidelines, therefore, name of functions should be in the `lower_case_with_underscores` style. Check it [PEP 8](https://www.python.org/dev/peps/pep-0008/)
> * You await function is correct but your decorator is not; therefore, this message is not received on the central system code. You are missing the `Action` word. You can check how it is done for `BootNotification` in the [example](https://github.com/mobilityhouse/ocpp/blob/master/examples/v16/central_system.py#L24)
> 
> Code example:
> OCPP:
> 
> * You have arguments which are not part of the StatusNotificationPayload like `evse_id` or `connector_status`. Check how the StatusNotificationPayload is implemented [here](https://github.com/mobilityhouse/ocpp/blob/fdfb5b1b33665dad13708b47226f48b56ee6b438/ocpp/v16/call.py#L213)
> * As a general tip, it is a good idea to open the OCPP manual and follow with the code the functions you are trying to implement (for e.g., page 46, OCPP 1.6 [manual](https://github.com/mobilityhouse/ocpp/blob/master/docs/v16/ocpp-1.6.pdf)
> * dateTime is format date-time as string, so your value should not have passed the validation. However, the validation does not fails, weird.
> 
> CP
> 
> ```
>     async def send_status_notification(self):
>         request = call.StatusNotificationPayload(
>             connector_id=1, error_code='NoError', status='Available')
>         response = await self.call(request)
> ```
> 
> Central system
> 
> ```
>     @on(Action.StatusNotification)
>     async def on_status_notification(self, connector_id: int,
>                                      error_code: str, status: str, **kwargs) -> Dict:
>         logging.info("status: %s, error_code: %s, optional: %s", status, error_code, kwargs)
>         return call_result.StatusNotificationPayload()
> ```
> 
> Running:
> 
> ```
> ✦ ➜ python3 charge_point.py 
> INFO:ocpp:CP_1: send [2,"2c329bdc-b86a-473e-848c-2510158bf3ca","BootNotification",{"chargePointModel":"Optimus","chargePointVendor":"The Mobility House"}]
> INFO:ocpp:CP_1: receive message [3,"2c329bdc-b86a-473e-848c-2510158bf3ca",{"currentTime":"2021-06-13T08:30:40.465251","interval":10,"status":"Accepted"}]
> Connected to central system.
> INFO:ocpp:CP_1: send [2,"d9df42c7-60ba-43c0-bc43-fc8c2c09d22a","StatusNotification",{"connectorId":1,"errorCode":"NoError","status":"Available"}]
> INFO:ocpp:CP_1: receive message [3,"d9df42c7-60ba-43c0-bc43-fc8c2c09d22a",{}]
> ```
> 
> ```
> ✦ ➜ python3 central_system.py 
> INFO:root:Server Started listening to new connections...
> INFO:root:Protocols Matched: ocpp1.6
> INFO:ocpp:CP_1: receive message [2,"2c329bdc-b86a-473e-848c-2510158bf3ca","BootNotification",{"chargePointModel":"Optimus","chargePointVendor":"The Mobility House"}]
> INFO:ocpp:CP_1: send [3,"2c329bdc-b86a-473e-848c-2510158bf3ca",{"currentTime":"2021-06-13T08:30:40.465251","interval":10,"status":"Accepted"}]
> INFO:ocpp:CP_1: receive message [2,"d9df42c7-60ba-43c0-bc43-fc8c2c09d22a","StatusNotification",{"connectorId":1,"errorCode":"NoError","status":"Available"}]
> INFO:root:status: Available, error_code: NoError, optional: {}
> INFO:ocpp:CP_1: send [3,"d9df42c7-60ba-43c0-bc43-fc8c2c09d22a",{}]
> ```

Hi, I need to correct some points of your reply.

> You await function is correct but your decorator is not; therefore, this message is not received on the central system code. You are missing the Action word. You can check how it is done for BootNotification in the example

Actually, he can use it as he did. Using the Enum is more pythonic and I encourage it as well, but in the end if he hardcodes it, the result is the same.

> You have arguments which are not part of the StatusNotificationPayload like evse_id or connector_status. Check how the StatusNotificationPayload is implemented here

If his idea is to use OCPP 2.0.1, then his arguments are correct. Check here: https://github.com/mobilityhouse/ocpp/blob/master/ocpp/v201/call.py#L384

**Comment by laysauchoa** [comment]
@antoniohuertas I suggest closing this question as it has been answered, and we can follow the timestamp in this [issue](https://github.com/mobilityhouse/ocpp/issues/216). 

True @tropxy However, the version was not mentioned in the Issue only later on the discussions.

**Comment by antoniohuertas** [comment]
Thank you for helping me  @laysauchoa @tropxy, best regards
